config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  
  validates :shop_name, presence: true
  validates :image, presence: true
  
  def favorites_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  after_action :store_action
  
  def store_action
    return unless request.get? 
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?)
      store_location_for(:user, post_images_path)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

    def user_params
      params.require(:user).permit(:name, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="sahdow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href=""><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "投稿一覧", post_images_path, class: "text-dark pr-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "投稿フォーム", new_post_image_path, class: "text-dark pr-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-dark pr-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path(current_user), class: "text-dark pr-3" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "text-dark pr-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "text-dark pr-3" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="d-flex justify-content-between">
          <div>
            <p>善良な市民同士て無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div>
            <%= link_to "さっそくはじめる！", new_user_registration_path, class: "text-white mt-2 mb-3" %>
            <ul class="p-0 list-unstyled mt-4">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License infomations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image) do %>
      <%= attachment_image_tag post_image, :image, class: "card-img-top" %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <p><%= attachment_image_tag post_image.user, :profile_image, size: "60x60", fallback: "no_image.jpg", class: "mt-3 rounded-circle" %></p>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to post_image_path(post_image), class: "text-dark" do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %> </span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> | </span>
          <span><%= link_to "#{ post_image.post_comments.count }コメント", post_image_path(post_image), class: "text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  
  <%= paginate post_images, theme: 'twitter-bootstrap-4' %>
</div>

app/views/post_images/index.html.erb
<%= render 'post_images/list', post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿用フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local: true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class: "form-control", placeholder: "ショップ名" %>
          </div>
          <%= f.text_area :caption, class: "form-control", rows: "3", placeholder: "コメントここに" %>
          <hr>
          <%= f.submit "投稿", class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-10 col-sm-8 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0 text-center font-weight-bold"><%= @post_image.shop_name %></h5>
      <div id="post-image w-100">
        <%= attachment_image_tag @post_image, :image, class: "w-100"%>
      </div>
      <div class="row">
        <div class="col-md-4 mt-3 text-center">
          <%= attachment_image_tag @post_image.user, :profile_image, size: "60x60", class: "rounded-circle", fallback: "no_image.jpg" %>
          <p class="mt-2"><i class="far fa-user pr-2"></i><%= @post_image.user.name %></p>
        </div>
        <div class="col-md-4 mt-3 text-center">
          <% if @post_image.favorites_by?(current_user) %>
            <%= link_to post_image_favorites_path(@post_image), method: :delete, class: "text-danger" do %>
              <i class="fas fa-heart fa-4x"></i>
              <p class="mt-1 text-dark">
                <span class="pr-2"><%= @post_image.favorites.count %></span>いいね！
              </p>
            <% end %>
          <% else %>
            <%= link_to post_image_favorites_path(@post_image), method: :post, class: "text-danger" do %>
              <i class="far fa-heart fa-4x"></i>
              <p class="mt-1 text-dark">
                <span class="pr-2"><%= @post_image.favorites.count %></span>いいね！
              </p>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-4 mt-3 text-center">
          <% if @post_image.user == current_user %>
            <%= link_to post_image_path(@post_image), method: :delete, class: "text-success" do %>
              <i class="fas fa-trash-alt fa-4x"></i>
              <p class="mt-1 text-dark">
                削除
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="image-show-footer m-3 bg-light rounded p-3">
        <p>説明：<%= @post_image.caption %></p>
        <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
      </div>
    </div>
  </div>
</div>

<div class="comments container">
  <div class="row no-gutters">
    <div class="col-md-10 col-sm-8 mx-2 mx-sm-auto shadow-lg rounded p-4 my-5">
      <p>コメント件数<%= @post_image.post_comments.count %></p>
      <% @post_image.post_comments.each do |post_comment| %>
        <div class="comment row my-2">
          <div class="comment-user-img col-md-3">
            <%= attachment_image_tag post_comment.user, :profile_image, size: '50x50', class: "rounded-circle" %>
          </div>
          <div class="comment-user-database col-md-4">
            <%= post_comment.user.name %>
            <%= post_comment.created_at.strftime( "%Y/%m/%d" ) %>
            <% if current_user == post_comment.user %>
            <div class="comment-delete">
              <%= link_to post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete do %>
                <i class="fas fa-trash-alt pr-2"></i><span>削除</span>
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="commet-user-comment col-md-5 p-2 bg-light">
            <%= post_comment.comment %>
          </div>
      </div>
      <% end %>
      <div class="new-comment mt-3">
        <p><i class="fas fa-comment fa-2x pr-3"></i>コメント</p>
        <%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
          <%= f.text_area :comment, row: '5', placeholder: "コメントをここに", class: "w-100" %>
          <%= f.submit '送信する', class: "btn btn-outline-info ml-auto d-block " %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>プロフィール画像</h2>
<%= form_with model: @user, local: true do |f| %>
  <label for="inputName"></label>
  <%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "名前" %>
  <%= attachment_image_tag @user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <%= f.submit "変更を保持" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="profile-container py-5 text^-center">
        <div class="profile-image">
          <%= attachment_image_tag @user, :profile_image, size: "150x150", format: 'jpeg', fallback: "no_image.jpg", class: "rounded-circle" %>
        </div>
        <div class="profile-date mt-3">
          <h4 class="profile-name pb-2"><i class="fas fa-user-check pr-2"></i><%= @user.name %></h4>
          <% if current_user == @user %>
            <p>
              <%= link_to "プロフィール編集", edit_user_path(@user) %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <%= render 'post_images/list', post_images: @post_images %>
    </div>
  </div>
</div>